delete from customer;
insert into customer(name) values ('Spencer');
insert into customer(name) values ('Christoph');
insert into customer(name) values ('Josh');
insert into customer(name) values ('Jürgen');
insert into customer(name) values ('Olga');
insert into customer(name) values ('Dr. Syer');
insert into customer(name) values ('Stéphane');
insert into customer(name) values ('Violetta');
insert into customer(name) values ('Yuxin');
insert into customer(name) values ('Madhura');